### ISSUE TITLE
Feature request: add support to frontend protocols like WAMP

### ISSUE THREAD

**Issue by HowardMei** [CloudI/CloudI#137]
Web Application Messaging Protocol [WAMP http://wamp.ws/] is a open source protocol in development targeting at Internet of Things [https://github.com/tavendo/WAMP/tree/master/spec].  

Cloudi aims to integrate backend services, but given its support to HTTP/Websocket services and more flexible messaging patterns, isn't it a perfect opportunity to showcase how natural it is to build a robust and scalable WAMP framework on top of its APIs? The transactional session or role-specific handling part of this protocol are what Cloudi lacks.  

Currently, the major implementations of WAMP like http://autobahn.ws/  or https://github.com/bwegh/erwa don't have many backend features Cloudi provides.  

If your great work could be a part of [Cloudi API be a part of WAMP spec v3] or even a super set of WAMP [add more logging, analyzing and management apis], a solid foundation for future light weight cloud/web application development will arise!

**Comment by okeuday** [comment]
Since this is just a single protocol which is specific to IoT, it is not clearly beneficial to CloudI functionality, so it is not being pursued as part of CloudI.  There is nothing preventing it being implemented with CloudI, it is just difficult to find a reason to include it with CloudI.
