### ISSUE TITLE
cloudi_service_filesystem LFUDA cache

### ISSUE THREAD

**Issue by okeuday** [CloudI/CloudI#150]
Need to weight the cache items with file_size/accesses to remove the largest weight values (and keep the cache size under the configured `files_size` value).

**Comment by abhi005** [comment]
@okeuday Hey, I would like to work on it. And since this is like mandatory requirement for my course work, so will make sure that it gets completed.

**Comment by okeuday** [comment]
@abhi005 Ok, just make changes on a fork of this repo.  There is a separate [cloudi_service_filesystem](https://github.com/CloudI/cloudi_service_filesystem) repo that can get updated after the merge to this repo (for hex packages it helps to have those service repos, though they are focused on internal service use).

The additional code needs to avoid exceeding the `files_size` limit while maintaining the cache, so it is best to read the file to determine its size (that approach doesn't have problems with checking a file's size before the file changes).  In the future, the Erlang/OTP `file` module could have a `file:read_file/2` function that only loads a file if its file size is at or below a provided limit, to avoid temporarily exceeding the `files_size` limit (not a concern for this issue).  The `read_files_init` and `read_files_refresh` functions have the current file loading logic.

To keep things simpler and avoid loading files on demand (to avoid requests having extra latency due to a cache miss) the LRU changes should be isolated to the `read_files_refresh` logic.  To remove file data based on size/accesses the total number of accesses (of all files) must be high enough to justify the removal (i.e., an LRU cache without accesses shouldn't remove file data).  There are other details, like probably needing entries for files that are not loaded to ensure cache misses get tracked as accesses.  Add functions as you need to but try to keep the same function name prefix for related ideas.

The LRU mode can be based on a `lru` argument to `cloudi_service_filesystem` that defaults to `false`.  When that argument is provided (as `{lru, true}`) this LRU logic can help to manage the file data loaded in-memory.

**Comment by okeuday** [comment]
@abhi005 I have been thinking about this a little bit more.  To keep memory usage a bit more minimal, these changes could rely on `#state{}` having a `lru_counts` field added that would be either a `cloudi_x_trie` data structure (argument `lru` == true) or `undefined` (argument `lru` == false).  Each access in `cloudi_service_handle_request` where `cloudi_x_trie:find(Name, Files)` returns `{ok, _}` can increment a counter in `lru_counts` for the `Name` path (using `cloudi_x_trie:update_counter/3`).

If the argument `lru` == true, then the argument `read` == [] (can add an assertion in `cloudi_service_init/4` to ensure that is true).

The `read_files_refresh` logic would want to have the `lru_counts` lookup processed in an order based on the counts, so that would require turning it into a list that is sorted based on the count integer.  There isn't an advantage to resetting the count or removing the entries in `lru_counts`, so it doesn't need to be modified each "refresh" time interval.  The `lru_counts` sorted list can be processed before the `fold_files/3` function is used in `read_files_refresh` to ensure those paths are loaded first based on their access count (highest processed first).

Currently, it is tracking the total size currently loaded and adjusting the files loaded based on what appears and disappears when the filesystem is checked each "refresh" time interval.  So, the `fold_files/3` usage with `lru` == true would need to be a little different.  That would likely mean creating a new `files` lookup based on the old `files` lookup each "refresh" time interval, so the new lookup is starting with 0 bytes.  To approach this, it is likely easiest to make a separate `read_files_refresh_lru` function based on the current `read_files_refresh` function before determining if the logic should be combined (the `read_files_refresh` function is already relatively large).

**Comment by okeuday** [comment]
@abhi005 I didn't get much time to think about this feature in the past, so my previous comments were not as well thought-out as they could have been and the title should really be LFRU instead of LRU.  After recent thoughts about this, I would like to implement the initial expiration algorithm as LFRU using an argument `{expire, true}`.  That can leave the source code open for future change to add other expiration algorithms if other algorithms are added (instead of true the algorithm name can be used as an atom, true will just represent the default algorithm and the expire argument will default to false).  I also will be improving the variable names so they use suffixes for variation ("New", "Next", "Old" prefixes should be suffixes to make it easier to see what data is changing) as other CloudI source code now does, though that is noisy in the commit and can cause merge problems.

So, let me take this issue.  After my changes it should be a bit more straight-forward to add a new expiration algorithm to the source code.

**Comment by okeuday** [comment]
After more reading, LFUDA appears to be the best choice for the default algorithm.  Instead of the argument as `expire`, using `replace` because it is more typical to talk about a cache replacement algorithm (avoids confusion, often cache descriptions use "evict" instead of "expire").  Still will provide the monotonic time in an easily accessible way, for potential use by an LRU-related algorithm in the future (in the source code).

**Comment by okeuday** [comment]
@abhi005 I added LRU too for comparison.  Feel free to create a pull request if you wanted to pursue other algorithms.
