### ISSUE TITLE
Main web page Here-Docs need quotes

### ISSUE THREAD

**Issue by PenelopeFudd** [CloudI/CloudI#158]
I viewed your website with interest, but was chagrined to see that http://cloudi.org/#Perl had backslashes in front of every $ in the code!

Apparently 
```
   cat << EOF > hello_world.pl 
```
is not the same as
```
   cat << 'EOF' > hello_world.pl
```

**Comment by okeuday** [comment]
I agree that approach would be better if it could be done in the same way for all shells.  I know that bash requires a final EOF while tcsh requires a final 'EOF'.  I am not sure about what other problems would occur in other shells.  It is best to not be bash-centric.

**Comment by okeuday** [comment]
Feel free to update an issue if you have a better idea.
