### ISSUE TITLE
install  cloudi_service_db_riak fail

### ISSUE THREAD

**Issue by DLive** [CloudI/CloudI#187]
Hi
I excute ./autogen.sh && ./configure  && make && sudo make install.
but i find the cloudi_service_db_riak is not install to /usr/local/lib/cloudi-1.5.0/lib folder。
how to install cloudi_service_db_riak module? 
thanks

**Comment by DLive** [comment]
it is no add  {app, cloudi_service_db_riak, [{incl_cond, include}, {mod_cond, all}, {app_file, keep}]} to the reltool.conf.in .
I add,and install success.
thanks.

**Comment by okeuday** [comment]
For some reason, the services cloudi_service_db_cassandra_cql, cloudi_service_db_riak, and cloudi_service_oauth1 were not added to the final installation but they are now included, using the same addition that you used.  Please report any other problems if you have any.  Thanks!
