### ISSUE TITLE
autogen.sh error

### ISSUE THREAD

**Issue by DLive** [CloudI/CloudI#189]
install error.
can you help me？
### error info:
[root@localhost src]# ./autogen.sh
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure:19101: error: possibly undefined macro: AC_CHECK_CLASS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/bin/autoconf failed with exit status: 1

### System Version: 
Centos 6.6 
### autoconf
[root@localhost src]# autoconf --version
autoconf (GNU Autoconf) 2.69
### automake
[root@localhost src]# automake --version
automake (GNU automake) 1.9
### libtool
[root@localhost src]# libtool --version
libtool (GNU libtool) 2.4.6

Thanks!

**Comment by DLive** [comment]
I resolve it.
I install autoconf automake with rpm. before it is install width source code.
thanks.

**Comment by okeuday** [comment]
Thank you for reporting it.  I think the m4 macro usage of `AU_ALIAS` must not be supported by autoconf 2.69, but I will need to look into it more to check that.  Thanks!

**Comment by okeuday** [comment]
For some reason this problem is typical to CentOS missing the `pkg-config` executable and its associated macro(s) (`rpm -ql pkg-config`).  I know you solved the problem locally yourself, just wanted to add a comment here for if the problem occurs in the future.

**Comment by DLive** [comment]
thank you
