### ISSUE TITLE
minor doc problem

### ISSUE THREAD

**Issue by bobgus** [CloudI/CloudI#202]
The directory:
  PREFIX/var/logs/cloudi/cloudi.log.

Should probably be:
 PREFIX/var/log/cloudi/cloudi.log.

**Comment by okeuday** [comment]
Thanks for reporting this.  The only instance of this problem should be at http://cloudi.org/faq.html#3_Running and it has been corrected in the repo https://github.com/CloudI/website/ (the docs will be updated in this repo at release-time).
