### ISSUE TITLE
Build/Install Requirements

### ISSUE THREAD

**Issue by bmccary** [CloudI/CloudI#213]
On my Ubuntu 17.10 machine, I was running into several build errors which issued from `rebar`. Unfortunately, there does not appear to be much error output when `rebar` generates an error. To aid a search engine, the relevant part of the error was:

```
external/cloudi_x_exometer: rebar_abort 
Makefile:1063: recipe for target 'rebar-compile' failed
```

Hopefully if someone types `cloudi exometer rebar abort` they'll get here. Unfortunately, pasting something like the above into a search engine yields a multitude of terse `rebar` errors.

After a little consideration, I copy/pasted the `rebar` command which caused the problem and added `--verbose 3`. Looking at the error messages, I realized that I need to install the following packages:

```
sudo apt install erlang-snmp erlang-eunit
```

In the end, I think the problem is partly a documentation/build problem and partly my problem. The CloudI documentation says to install: `sudo apt install erlang`. On Ubuntu 17.10, this is a meta-package which depends on many of the `erlang-*` packages, including (I presume) all the ones necessary to build CloudI. However, I had previously installed the several `erlang-*` packages I needed for a different project separately, but not the `erlang` meta package, so I did not have `erlang-snmp` or `erlang-eunit`. So assuming my existing erlang environment was sufficient (and not installing the meta-package `erlang` as instructed) was my problem. But I think the terseness of the error from the build system made figuring out the problem more difficult than necessary.

I'd suggest the following modifications.

1. Add a note somewhere that `erlang-snmp` and `erlang-eunit` are specifically necessary on Ubuntu.
2. And/or make the `rebar-compile` part of the build process log its errors verbosely somewhere conspicuous.
3. And/or make the `./configure` fail if `erlang-snmp` or `erlang-eunit` are absent.

I look forward to trying out CloudI!

**Comment by okeuday** [comment]
Thank you for filing this issue.  It should be relatively easy to add an `erlang-snmp` and `erlang-eunit` check to the configure script.  Adding verbose to the rebar usage is a good change.

Also, there is an Alpine Linux 3.8 package that provides the 1.7.3 release and there is a repository for Docker containers at https://github.com/CloudI/containers which may be helpful.

**Comment by okeuday** [comment]
Suggestions added to the `develop` branch.  Thanks!
