### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by webdeb** [CloudI/CloudI#221]
a service like cloudi should have its own official docker image, for a quick start.

To get an experience like:
```
docker run -p 8080:80 coudi 
cloudi deploy ./some-module localhost:8080
```

**Comment by okeuday** [comment]
You are looking for the https://github.com/CloudI/containers repository.  I haven't yet updated the version there for using 1.8.0, but that should be what you are expecting.  Tell me if not.  I can update the version sometime in the next few days.

**Comment by webdeb** [comment]
Ah cool, thank you! I'll check it out 👍

**Comment by webdeb** [comment]
Tried to start the image (to then access the dashboard via localhost:6464/cloudi) without any luck.
It just printed:

```
$ docker run -p 6464:6464 cloudi/cloudi:v1.7.5
Unable to find image 'cloudi/cloudi:v1.7.5' locally
v1.7.5: Pulling from cloudi/cloudi
6c40cc604d8e: Pull complete
7d81091abcbe: Pull complete
8c68b7865634: Pull complete
20aeef4d97d7: Pull complete
Digest: sha256:ef57d53d4f04704fb7aca4ffe8d02df9c6b047c942b0ec1b5ac05fddee0b2b8e
Status: Downloaded newer image for cloudi/cloudi:v1.7.5
Exec: /usr/lib/cloudi-1.7.5/erts-10.2.1/bin/erlexec -boot /usr/lib/cloudi-1.7.5/releases/1/cloudi -config /usr/lib/cloudi-1.7.5/etc/app.config -args_file /usr/lib/cloudi-1.7.5/etc/vm.args -mode embedded -shutdown_time 65000 -- console
Root: /usr/lib/cloudi-1.7.5
Eshell V10.2.1  (abort with ^G)
(cloudi@8e4b1e0c856b)1> *** Terminating erlang (cloudi@8e4b1e0c856b)
```

PS: Maybe its better to close that issue here, and move to cloudi/containers ?

**Comment by webdeb** [comment]
It works, was my fault, great!
