### ISSUE TITLE
Elixir example

### ISSUE THREAD

**Issue by webdeb** [CloudI/CloudI#222]
Hi @okeuday could you please provide a simple mix project example.
This would be very helpful.

**Comment by okeuday** [comment]
Hi @webdeb, https://github.com/CloudI/CloudI/tree/develop/examples currently has an Elixir example.  So, that example is an Elixir internal service.

Embedding CloudI into an Erlang/OTP application currently only has an Erlang example, but that is likely less common.  It is best to try the Elixir example first.  If you needed the embedded approach with Elixir it would be simplest with the remote_dependency approach using mix.  The local_install approach is better, but I have only pursued that with rebar2.

**Comment by webdeb** [comment]
Ah, ok. You would need rebar3 for it to work, right?

**Comment by okeuday** [comment]
@webdeb https://github.com/CloudI/CloudI/tree/develop/examples/Elixir.HelloWorld uses mix, the other examples use rebar2 or rebar3

**Comment by okeuday** [comment]
@webdeb Closing the issue for now.  Can reopen if you think something should be added to changed.
